# Generated by Django 3.0.4 on 2020-04-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200403_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmessage',
            name='subject',
        ),
    ]
