# Generated by Django 3.0.4 on 2020-03-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0002_emlak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('emlak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emlak.Emlak')),
            ],
        ),
    ]
