# Generated by Django 3.0.4 on 2020-03-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
