# Generated by Django 3.0.4 on 2020-04-03 20:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0004_auto_20200318_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlak',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
