# Generated by Django 3.0.4 on 2020-04-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0005_auto_20200403_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='emlak',
            name='slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emlak',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emlak',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emlak',
            name='rooms',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
