# Generated by Django 3.0.4 on 2020-04-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0006_auto_20200405_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlak',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
