# Generated by Django 3.0.3 on 2020-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0012_auto_20200422_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlak',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
