# Generated by Django 3.0.4 on 2020-05-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0014_emlak_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emlak',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='emlak',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
