# Generated by Django 3.0.4 on 2020-05-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0017_emlak_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emlak',
            name='image2',
        ),
    ]
